$ProductsImagesDir = Join-Path (Get-Location) "uploads\productsImages"

Write-Host "ProductsImagesDir: $ProductsImagesDir"

if (!(Test-Path $ProductsImagesDir)) {
  Write-Host "Folder not found: $ProductsImagesDir" -ForegroundColor Red
  exit 1
}

$Data = @'
6 "Топинамбур полезный" "/productsImages/product_6/images/topinambur.jpg"
7 "Морковь каротель" "/productsImages/product_7/images/carrots.jpg"
8 "Чеснок дикий" "/productsImages/product_8/images/garlic.jpg"
9 "Мята перечная" "/productsImages/product_9/images/herbs.jpg"
10 "Рукола пряная" "/productsImages/product_10/images/lettuce.jpg"
11 "Редис белый" "/productsImages/product_11/images/radish.jpg"
12 "Топинамбур полезный" "/productsImages/product_12/images/topinambur.jpg"
13 "Сельдерей черешковый" "/productsImages/product_13/images/greens.jpg"
14 "Кабачок сквош" "/productsImages/product_14/images/zucchini.jpg"
15 "Микрозелень гороха" "/productsImages/product_15/images/greens.jpg"
17 "Кабачки нежные цукини" "/productsImages/product_17/images/zucchini.jpg"
18 "Салат айсберг хрустящий" "/productsImages/product_18/images/lettuce.jpg"
19 "Шпинат витаминный" "/productsImages/product_19/images/lettuce.jpg"
20 "Шпинат витаминный" "/productsImages/product_20/images/lettuce.jpg"
21 "Салат латук" "/productsImages/product_21/images/lettuce.jpg"
22 "Перец рамиро сладкий" "/productsImages/product_22/images/peppers.jpg"
23 "Спаржа зеленая" "/productsImages/product_23/images/greens.jpg"
24 "Картофель молодой фермерский" "/productsImages/product_24/images/potatoes.jpg"
25 "Петрушка листовая нежная" "/productsImages/product_25/images/herbs.jpg"
26 "Лук-порей" "/productsImages/product_26/images/onions.jpg"
27 "Кабачок сквош" "/productsImages/product_27/images/zucchini.jpg"
28 "Капуста пекинская" "/productsImages/product_28/images/cabbage.jpg"
29 "Чеснок дикий" "/productsImages/product_29/images/garlic.jpg"
30 "Цветная капуста оранжевая" "/productsImages/product_30/images/cabbage.jpg"
31 "Салат латук" "/productsImages/product_31/images/lettuce.jpg"
32 "Мята перечная" "/productsImages/product_32/images/herbs.jpg"
33 "Сельдерей черешковый" "/productsImages/product_33/images/greens.jpg"
34 "Мята перечная" "/productsImages/product_34/images/herbs.jpg"
35 "Салат айсберг хрустящий" "/productsImages/product_35/images/lettuce.jpg"
36 "Перец халапеньо" "/productsImages/product_36/images/peppers.jpg"
37 "Салат айсберг хрустящий" "/productsImages/product_37/images/lettuce.jpg"
38 "Рукола пряная" "/productsImages/product_38/images/lettuce.jpg"
39 "Лук-порей" "/productsImages/product_39/images/onions.jpg"
40 "Брокколи зеленая" "/productsImages/product_40/images/cabbage.jpg"
41 "Лук-порей" "/productsImages/product_41/images/onions.jpg"
42 "Салат латук" "/productsImages/product_42/images/lettuce.jpg"
43 "Сельдерей черешковый" "/productsImages/product_43/images/greens.jpg"
44 "Чеснок свежий урожай" "/productsImages/product_44/images/garlic.jpg"
45 "Рукола пряная" "/productsImages/product_45/images/lettuce.jpg"
46 "Баклажаны синие длинные" "/productsImages/product_46/images/eggplants.jpg"
47 "Чеснок дикий" "/productsImages/product_47/images/garlic.jpg"
48 "Свекла столовая в пучке" "/productsImages/product_48/images/beetroot.jpg"
49 "Помидоры розовые бычье сердце" "/productsImages/product_49/images/tomatoes.jpg"
50 "Кабачок сквош" "/productsImages/product_50/images/zucchini.jpg"
51 "Перец халапеньо" "/productsImages/product_51/images/peppers.jpg"
52 "Картофель красный мытый" "/productsImages/product_52/images/potatoes.jpg"
53 "Огурцы пупырчатые" "/productsImages/product_53/images/cucumbers.jpg"
54 "Салат айсберг хрустящий" "/productsImages/product_54/images/lettuce.jpg"
55 "Помидоры розовые бычье сердце" "/productsImages/product_55/images/tomatoes.jpg"
56 "Картофель красный мытый" "/productsImages/product_56/images/potatoes.jpg"
57 "Картофель мытый" "/productsImages/product_57/images/potatoes.jpg"
58 "Мята перечная" "/productsImages/product_58/images/herbs.jpg"
59 "Баклажаны синие длинные" "/productsImages/product_59/images/eggplants.jpg"
60 "Редис белый" "/productsImages/product_60/images/radish.jpg"
61 "Морковь молодая мытая" "/productsImages/product_61/images/carrots.jpg"
62 "Капуста пекинская" "/productsImages/product_62/images/cabbage.jpg"
63 "Помидоры розовые бычье сердце" "/productsImages/product_63/images/tomatoes.jpg"
64 "Топинамбур полезный" "/productsImages/product_64/images/topinambur.jpg"
65 "Петрушка листовая нежная" "/productsImages/product_65/images/herbs.jpg"
66 "Зелень петрушка+укроп" "/productsImages/product_66/images/herbs.jpg"
67 "Брокколи зеленая" "/productsImages/product_67/images/cabbage.jpg"
68 "Тыква голосемянная" "/productsImages/product_68/images/pumpkin.jpg"
69 "Лук репчатый золотистый" "/productsImages/product_69/images/onions.jpg"
70 "Цветная капуста оранжевая" "/productsImages/product_70/images/cabbage.jpg"
71 "Лук-порей" "/productsImages/product_71/images/onions.jpg"
72 "Розмарин душистый" "/productsImages/product_72/images/herbs.jpg"
73 "Перец рамиро сладкий" "/productsImages/product_73/images/peppers.jpg"
74 "Помидоры розовые бычье сердце" "/productsImages/product_74/images/tomatoes.jpg"
75 "Салат латук" "/productsImages/product_75/images/lettuce.jpg"
76 "Баклажаны синие длинные" "/productsImages/product_76/images/eggplants.jpg"
77 "Морковь молодая мытая" "/productsImages/product_77/images/carrots.jpg"
78 "Редис белый" "/productsImages/product_78/images/radish.jpg"
79 "Сельдерей черешковый" "/productsImages/product_79/images/greens.jpg"
80 "Кабачок сквош" "/productsImages/product_80/images/zucchini.jpg"
81 "Зелень петрушка+укроп" "/productsImages/product_81/images/herbs.jpg"
82 "Кабачок сквош" "/productsImages/product_82/images/zucchini.jpg"
83 "Редис сочный пучковый" "/productsImages/product_83/images/radish.jpg"
84 "Патиссоны мини" "/productsImages/product_84/images/zucchini.jpg"
85 "Шпинат витаминный" "/productsImages/product_85/images/lettuce.jpg"
86 "Баклажаны синие длинные" "/productsImages/product_86/images/eggplants.jpg"
87 "Базилик фиолетовый" "/productsImages/product_87/images/herbs.jpg"
88 "Помидоры черри сладкие" "/productsImages/product_88/images/tomatoes.jpg"
89 "Кабачок сквош" "/productsImages/product_89/images/zucchini.jpg"
90 "Тыква мускатная сладкая" "/productsImages/product_90/images/pumpkin.jpg"
91 "Лук-порей" "/productsImages/product_91/images/onions.jpg"
92 "Кабачки нежные цукини" "/productsImages/product_92/images/zucchini.jpg"
93 "Рукола пряная" "/productsImages/product_93/images/lettuce.jpg"
94 "Картофель красный мытый" "/productsImages/product_94/images/potatoes.jpg"
95 "Помидоры черри сладкие" "/productsImages/product_95/images/tomatoes.jpg"
96 "Тыква мускатная сладкая" "/productsImages/product_96/images/pumpkin.jpg"
97 "Кабачки нежные цукини" "/productsImages/product_97/images/zucchini.jpg"
98 "Капуста пекинская" "/productsImages/product_98/images/cabbage.jpg"
99 "Лук-порей" "/productsImages/product_99/images/onions.jpg"
100 "Морковь молодая мытая" "/productsImages/product_100/images/carrots.jpg"
101 "Кабачки жареные (заготовка)" "/productsImages/product_101/images/zucchini.jpg"
102 "Перец халапеньо" "/productsImages/product_102/images/peppers.jpg"
103 "Спаржа зеленая" "/productsImages/product_103/images/greens.jpg"
104 "Розмарин душистый" "/productsImages/product_104/images/herbs.jpg"
105 "Микрозелень гороха" "/productsImages/product_105/images/greens.jpg"
106 "Баклажаны синие длинные" "/productsImages/product_106/images/eggplants.jpg"
107 "Салат латук" "/productsImages/product_107/images/lettuce.jpg"
108 "Чеснок дикий" "/productsImages/product_108/images/garlic.jpg"
109 "Сельдерей черешковый" "/productsImages/product_109/images/greens.jpg"
110 "Шпинат витаминный" "/productsImages/product_110/images/lettuce.jpg"
111 "Рукола пряная" "/productsImages/product_111/images/lettuce.jpg"
112 "Базилик фиолетовый" "/productsImages/product_112/images/herbs.jpg"
113 "Цветная капуста оранжевая" "/productsImages/product_113/images/cabbage.jpg"
114 "Цветная капуста оранжевая" "/productsImages/product_114/images/cabbage.jpg"
115 "Розмарин душистый" "/productsImages/product_115/images/herbs.jpg"
116 "Мята перечная" "/productsImages/product_116/images/herbs.jpg"
117 "Мята перечная" "/productsImages/product_117/images/herbs.jpg"
118 "Картофель молодой фермерский" "/productsImages/product_118/images/potatoes.jpg"
119 "Чеснок дикий" "/productsImages/product_119/images/garlic.jpg"
120 "Шпинат витаминный" "/productsImages/product_120/images/lettuce.jpg"
121 "Морковь молодая мытая" "/productsImages/product_121/images/carrots.jpg"
122 "Перец халапеньо" "/productsImages/product_122/images/peppers.jpg"
123 "Баклажаны синие длинные" "/productsImages/product_123/images/eggplants.jpg"
124 "Редис сочный пучковый" "/productsImages/product_124/images/radish.jpg"
125 "Редис белый" "/productsImages/product_125/images/radish.jpg"
126 "Сельдерей черешковый" "/productsImages/product_126/images/greens.jpg"
127 "Лук репчатый золотистый" "/productsImages/product_127/images/onions.jpg"
128 "Редис белый" "/productsImages/product_128/images/radish.jpg"
129 "Розмарин душистый" "/productsImages/product_129/images/herbs.jpg"
130 "Чеснок дикий" "/productsImages/product_130/images/garlic.jpg"
131 "Чеснок дикий" "/productsImages/product_131/images/garlic.jpg"
132 "Кинза свежая" "/productsImages/product_132/images/herbs.jpg"
133 "Мята перечная" "/productsImages/product_133/images/herbs.jpg"
134 "Капуста пекинская" "/productsImages/product_134/images/cabbage.jpg"
135 "Цветная капуста оранжевая" "/productsImages/product_135/images/cabbage.jpg"
136 "Кинза свежая" "/productsImages/product_136/images/herbs.jpg"
137 "Кинза свежая" "/productsImages/product_137/images/herbs.jpg"
138 "Перец болгарский красный" "/productsImages/product_138/images/peppers.jpg"
139 "Розмарин душистый" "/productsImages/product_139/images/herbs.jpg"
140 "Чеснок свежий урожай" "/productsImages/product_140/images/garlic.jpg"
141 "Капуста пекинская" "/productsImages/product_141/images/cabbage.jpg"
142 "Зелень петрушка+укроп" "/productsImages/product_142/images/herbs.jpg"
143 "Кабачок сквош" "/productsImages/product_143/images/zucchini.jpg"
144 "Микрозелень гороха" "/productsImages/product_144/images/greens.jpg"
145 "Салат айсберг хрустящий" "/productsImages/product_145/images/lettuce.jpg"
146 "Свекла бордовая" "/productsImages/product_146/images/beetroot.jpg"
147 "Кабачки жареные (заготовка)" "/productsImages/product_147/images/zucchini.jpg"
148 "Микрозелень гороха" "/productsImages/product_148/images/greens.jpg"
149 "Огурцы хрустящие с грядки" "/productsImages/product_149/images/cucumbers.jpg"
150 "Огурцы хрустящие с грядки" "/productsImages/product_150/images/cucumbers.jpg"
151 "Помидоры черри сладкие" "/productsImages/product_151/images/tomatoes.jpg"
152 "Капуста пекинская" "/productsImages/product_152/images/cabbage.jpg"
153 "Огурцы пупырчатые" "/productsImages/product_153/images/cucumbers.jpg"
154 "Кольраби нежная" "/productsImages/product_154/images/cabbage.jpg"
155 "Спаржа зеленая" "/productsImages/product_155/images/greens.jpg"
156 "Кабачки жареные (заготовка)" "/productsImages/product_156/images/zucchini.jpg"
157 "Брокколи зеленая" "/productsImages/product_157/images/cabbage.jpg"
158 "Кольраби нежная" "/productsImages/product_158/images/cabbage.jpg"
159 "Помидоры розовые бычье сердце" "/productsImages/product_159/images/tomatoes.jpg"
160 "Лук репчатый золотистый" "/productsImages/product_160/images/onions.jpg"
161 "Огурцы пупырчатые" "/productsImages/product_161/images/cucumbers.jpg"
162 "Кабачки нежные цукини" "/productsImages/product_162/images/zucchini.jpg"
163 "Перец рамиро сладкий" "/productsImages/product_163/images/peppers.jpg"
164 "Морковь молодая мытая" "/productsImages/product_164/images/carrots.jpg"
165 "Кабачки нежные цукини" "/productsImages/product_165/images/zucchini.jpg"
166 "Чеснок дикий" "/productsImages/product_166/images/garlic.jpg"
167 "Базилик фиолетовый" "/productsImages/product_167/images/herbs.jpg"
168 "Шпинат витаминный" "/productsImages/product_168/images/lettuce.jpg"
169 "Спаржа зеленая" "/productsImages/product_169/images/greens.jpg"
170 "Укроп душистый пучок" "/productsImages/product_170/images/herbs.jpg"
171 "Салат латук" "/productsImages/product_171/images/lettuce.jpg"
172 "Кинза свежая" "/productsImages/product_172/images/herbs.jpg"
173 "Кабачки жареные (заготовка)" "/productsImages/product_173/images/zucchini.jpg"
174 "Баклажаны синие длинные" "/productsImages/product_174/images/eggplants.jpg"
175 "Кабачки жареные (заготовка)" "/productsImages/product_175/images/zucchini.jpg"
176 "Брокколи зеленая" "/productsImages/product_176/images/cabbage.jpg"
177 "Кинза свежая" "/productsImages/product_177/images/herbs.jpg"
178 "Огурцы хрустящие с грядки" "/productsImages/product_178/images/cucumbers.jpg"
179 "Салат латук" "/productsImages/product_179/images/lettuce.jpg"
180 "Кинза свежая" "/productsImages/product_180/images/herbs.jpg"
181 "Кольраби нежная" "/productsImages/product_181/images/cabbage.jpg"
182 "Капуста пекинская" "/productsImages/product_182/images/cabbage.jpg"
183 "Свекла бордовая" "/productsImages/product_183/images/beetroot.jpg"
184 "Лук-порей" "/productsImages/product_184/images/onions.jpg"
185 "Свекла столовая в пучке" "/productsImages/product_185/images/beetroot.jpg"
186 "Редис белый" "/productsImages/product_186/images/radish.jpg"
187 "Лук репчатый золотистый" "/productsImages/product_187/images/onions.jpg"
188 "Помидоры черри сладкие" "/productsImages/product_188/images/tomatoes.jpg"
189 "Чеснок дикий" "/productsImages/product_189/images/garlic.jpg"
190 "Кабачок сквош" "/productsImages/product_190/images/zucchini.jpg"
191 "Картофель для варки" "/productsImages/product_191/images/potatoes.jpg"
192 "Укроп душистый пучок" "/productsImages/product_192/images/herbs.jpg"
193 "Помидоры черри сладкие" "/productsImages/product_193/images/tomatoes.jpg"
194 "Капуста пекинская" "/productsImages/product_194/images/cabbage.jpg"
195 "Рукола пряная" "/productsImages/product_195/images/lettuce.jpg"
196 "Кабачки нежные цукини" "/productsImages/product_196/images/zucchini.jpg"
197 "Кабачки жареные (заготовка)" "/productsImages/product_197/images/zucchini.jpg"
198 "Розмарин душистый" "/productsImages/product_198/images/herbs.jpg"
199 "Редька дайкон сладкая" "/productsImages/product_199/images/radish.jpg"
200 "Свекла бордовая" "/productsImages/product_200/images/beetroot.jpg"
201 "Свекла бордовая" "/productsImages/product_201/images/beetroot.jpg"
202 "Кабачки жареные (заготовка)" "/productsImages/product_202/images/zucchini.jpg"
203 "Капуста пекинская" "/productsImages/product_203/images/cabbage.jpg"
204 "Тыква голосемянная" "/productsImages/product_204/images/pumpkin.jpg"
205 "Спаржа зеленая" "/productsImages/product_205/images/greens.jpg"
206 "Редис сочный пучковый" "/productsImages/product_206/images/radish.jpg"
207 "Перец рамиро сладкий" "/productsImages/product_207/images/peppers.jpg"
208 "Лук-порей" "/productsImages/product_208/images/onions.jpg"
209 "Микрозелень гороха" "/productsImages/product_209/images/greens.jpg"
210 "Сельдерей черешковый" "/productsImages/product_210/images/greens.jpg"
211 "Перец рамиро сладкий" "/productsImages/product_211/images/peppers.jpg"
212 "Кольраби нежная" "/productsImages/product_212/images/cabbage.jpg"
213 "Брокколи зеленая" "/productsImages/product_213/images/cabbage.jpg"
214 "Морковь каротель" "/productsImages/product_214/images/carrots.jpg"
215 "Брокколи зеленая" "/productsImages/product_215/images/cabbage.jpg"
216 "Чеснок дикий" "/productsImages/product_216/images/garlic.jpg"
217 "Редька дайкон сладкая" "/productsImages/product_217/images/radish.jpg"
218 "Чеснок дикий" "/productsImages/product_218/images/garlic.jpg"
219 "Шпинат витаминный" "/productsImages/product_219/images/lettuce.jpg"
220 "Помидоры розовые бычье сердце" "/productsImages/product_220/images/tomatoes.jpg"
221 "Петрушка листовая нежная" "/productsImages/product_221/images/herbs.jpg"
222 "Редис белый" "/productsImages/product_222/images/radish.jpg"
223 "Перец халапеньо" "/productsImages/product_223/images/peppers.jpg"
224 "Редис белый" "/productsImages/product_224/images/radish.jpg"
225 "Помидоры розовые бычье сердце" "/productsImages/product_225/images/tomatoes.jpg"
226 "Перец рамиро сладкий" "/productsImages/product_226/images/peppers.jpg"
227 "Картофель молодой фермерский" "/productsImages/product_227/images/potatoes.jpg"
228 "Свекла бордовая" "/productsImages/product_228/images/beetroot.jpg"
229 "Тыква мускатная сладкая" "/productsImages/product_229/images/pumpkin.jpg"
230 "Свекла бордовая" "/productsImages/product_230/images/beetroot.jpg"
231 "Розмарин душистый" "/productsImages/product_231/images/herbs.jpg"
232 "Зелень петрушка+укроп" "/productsImages/product_232/images/herbs.jpg"
233 "Мята перечная" "/productsImages/product_233/images/herbs.jpg"
234 "Перец рамиро сладкий" "/productsImages/product_234/images/peppers.jpg"
235 "Картофель молодой фермерский" "/productsImages/product_235/images/potatoes.jpg"
236 "Спаржа зеленая" "/productsImages/product_236/images/greens.jpg"
237 "Редис белый" "/productsImages/product_237/images/radish.jpg"
238 "Баклажаны синие длинные" "/productsImages/product_238/images/eggplants.jpg"
239 "Шпинат витаминный" "/productsImages/product_239/images/lettuce.jpg"
240 "Тыква мускатная сладкая" "/productsImages/product_240/images/pumpkin.jpg"
241 "Патиссоны мини" "/productsImages/product_241/images/zucchini.jpg"
242 "Лук-порей" "/productsImages/product_242/images/onions.jpg"
243 "Помидоры для салата" "/productsImages/product_243/images/tomatoes.jpg"
244 "Шпинат витаминный" "/productsImages/product_244/images/lettuce.jpg"
245 "Перец болгарский красный" "/productsImages/product_245/images/peppers.jpg"
246 "Капуста белокочанная свежая" "/productsImages/product_246/images/cabbage.jpg"
247 "Помидоры черри сладкие" "/productsImages/product_247/images/tomatoes.jpg"
248 "Зелень петрушка+укроп" "/productsImages/product_248/images/herbs.jpg"
249 "Кинза свежая" "/productsImages/product_249/images/herbs.jpg"
250 "Редис белый" "/productsImages/product_250/images/radish.jpg"
251 "Брокколи зеленая" "/productsImages/product_251/images/cabbage.jpg"
252 "Чеснок свежий урожай" "/productsImages/product_252/images/garlic.jpg"
253 "Перец рамиро сладкий" "/productsImages/product_253/images/peppers.jpg"
254 "Тыква голосемянная" "/productsImages/product_254/images/pumpkin.jpg"
255 "Огурцы пупырчатые" "/productsImages/product_255/images/cucumbers.jpg"
256 "Чеснок свежий урожай" "/productsImages/product_256/images/garlic.jpg"
257 "Огурцы пупырчатые" "/productsImages/product_257/images/cucumbers.jpg"
258 "Тыква голосемянная" "/productsImages/product_258/images/pumpkin.jpg"
259 "Кабачки жареные (заготовка)" "/productsImages/product_259/images/zucchini.jpg"
260 "Салат айсберг хрустящий" "/productsImages/product_260/images/lettuce.jpg"
261 "Капуста белокочанная свежая" "/productsImages/product_261/images/cabbage.jpg"
262 "Розмарин душистый" "/productsImages/product_262/images/herbs.jpg"
263 "Салат айсберг хрустящий" "/productsImages/product_263/images/lettuce.jpg"
264 "Салат латук" "/productsImages/product_264/images/lettuce.jpg"
265 "Редис белый" "/productsImages/product_265/images/radish.jpg"
266 "Салат латук" "/productsImages/product_266/images/lettuce.jpg"
267 "Кинза свежая" "/productsImages/product_267/images/herbs.jpg"
268 "Тыква мускатная сладкая" "/productsImages/product_268/images/pumpkin.jpg"
269 "Патиссоны мини" "/productsImages/product_269/images/zucchini.jpg"
270 "Морковь молодая мытая" "/productsImages/product_270/images/carrots.jpg"
271 "Чеснок дикий" "/productsImages/product_271/images/garlic.jpg"
272 "Кабачки нежные цукини" "/productsImages/product_272/images/zucchini.jpg"
273 "Редис сочный пучковый" "/productsImages/product_273/images/radish.jpg"
274 "Картофель молодой фермерский" "/productsImages/product_274/images/potatoes.jpg"
275 "Свекла столовая в пучке" "/productsImages/product_275/images/beetroot.jpg"
276 "Укроп душистый пучок" "/productsImages/product_276/images/herbs.jpg"
277 "Чеснок свежий урожай" "/productsImages/product_277/images/garlic.jpg"
278 "Помидоры розовые бычье сердце" "/productsImages/product_278/images/tomatoes.jpg"
279 "Капуста белокочанная свежая" "/productsImages/product_279/images/cabbage.jpg"
280 "Чеснок дикий" "/productsImages/product_280/images/garlic.jpg"
281 "Брокколи зеленая" "/productsImages/product_281/images/cabbage.jpg"
282 "Перец рамиро сладкий" "/productsImages/product_282/images/peppers.jpg"
283 "Петрушка листовая нежная" "/productsImages/product_283/images/herbs.jpg"
284 "Салат айсберг хрустящий" "/productsImages/product_284/images/lettuce.jpg"
285 "Перец болгарский красный" "/productsImages/product_285/images/peppers.jpg"
286 "Салат айсберг хрустящий" "/productsImages/product_286/images/lettuce.jpg"
287 "Укроп душистый пучок" "/productsImages/product_287/images/herbs.jpg"
288 "Зелень петрушка+укроп" "/productsImages/product_288/images/herbs.jpg"
289 "Сельдерей черешковый" "/productsImages/product_289/images/greens.jpg"
290 "Сельдерей черешковый" "/productsImages/product_290/images/greens.jpg"
291 "Лук репчатый золотистый" "/productsImages/product_291/images/onions.jpg"
292 "Кабачки нежные цукини" "/productsImages/product_292/images/zucchini.jpg"
293 "Петрушка листовая нежная" "/productsImages/product_293/images/herbs.jpg"
294 "Перец халапеньо" "/productsImages/product_294/images/peppers.jpg"
295 "Морковь каротель" "/productsImages/product_295/images/carrots.jpg"
296 "Цветная капуста оранжевая" "/productsImages/product_296/images/cabbage.jpg"
297 "Редис белый" "/productsImages/product_297/images/radish.jpg"
298 "Зелень петрушка+укроп" "/productsImages/product_298/images/herbs.jpg"
299 "Кольраби нежная" "/productsImages/product_299/images/cabbage.jpg"
300 "Кабачки нежные цукини" "/productsImages/product_300/images/zucchini.jpg"
301 "Тыква голосемянная" "/productsImages/product_301/images/pumpkin.jpg"
302 "Морковь каротель" "/productsImages/product_302/images/carrots.jpg"
303 "Домашняя свекла" "/productsImages/product_303/images/beetroot.jpg"
304 "Чеснок свежий урожай" "/productsImages/product_304/images/garlic.jpg"
305 "Брокколи зеленая" "/productsImages/product_305/images/cabbage.jpg"
306 "Рукола пряная" "/productsImages/product_306/images/lettuce.jpg"
307 "Кабачок сквош" "/productsImages/product_307/images/zucchini.jpg"
308 "Рукола пряная" "/productsImages/product_308/images/lettuce.jpg"
309 "Капуста пекинская" "/productsImages/product_309/images/cabbage.jpg"
310 "Свекла столовая в пучке" "/productsImages/product_310/images/beetroot.jpg"
311 "Редис белый" "/productsImages/product_311/images/radish.jpg"
312 "Сельдерей черешковый" "/productsImages/product_312/images/greens.jpg"
313 "Базилик фиолетовый" "/productsImages/product_313/images/herbs.jpg"
314 "Морковь каротель" "/productsImages/product_314/images/carrots.jpg"
315 "Баклажаны синие длинные" "/productsImages/product_315/images/eggplants.jpg"
316 "Тыква голосемянная" "/productsImages/product_316/images/pumpkin.jpg"
317 "Свекла столовая в пучке" "/productsImages/product_317/images/beetroot.jpg"
318 "Перец болгарский красный" "/productsImages/product_318/images/peppers.jpg"
319 "Редька дайкон сладкая" "/productsImages/product_319/images/radish.jpg"
320 "Спаржа зеленая" "/productsImages/product_320/images/greens.jpg"
321 "Шпинат витаминный" "/productsImages/product_321/images/lettuce.jpg"
322 "Салат латук" "/productsImages/product_322/images/lettuce.jpg"
323 "Салат латук" "/productsImages/product_323/images/lettuce.jpg"
324 "Морковь каротель" "/productsImages/product_324/images/carrots.jpg"
325 "Свекла бордовая" "/productsImages/product_325/images/beetroot.jpg"
326 "Спаржа зеленая" "/productsImages/product_326/images/greens.jpg"
327 "Капуста пекинская" "/productsImages/product_327/images/cabbage.jpg"
328 "Морковь молодая мытая" "/productsImages/product_328/images/carrots.jpg"
329 "Патиссоны мини" "/productsImages/product_329/images/zucchini.jpg"
330 "Рукола пряная" "/productsImages/product_330/images/lettuce.jpg"
331 "Тыква мускатная сладкая" "/productsImages/product_331/images/pumpkin.jpg"
332 "Цветная капуста оранжевая" "/productsImages/product_332/images/cabbage.jpg"
333 "Свекла столовая в пучке" "/productsImages/product_333/images/beetroot.jpg"
334 "Брокколи зеленая" "/productsImages/product_334/images/cabbage.jpg"
335 "Перец болгарский красный" "/productsImages/product_335/images/peppers.jpg"
336 "Свекла столовая в пучке" "/productsImages/product_336/images/beetroot.jpg"
337 "Свекла бордовая" "/productsImages/product_337/images/beetroot.jpg"
338 "Кабачки нежные цукини" "/productsImages/product_338/images/zucchini.jpg"
339 "Перец халапеньо" "/productsImages/product_339/images/peppers.jpg"
340 "Микрозелень гороха" "/productsImages/product_340/images/greens.jpg"
341 "Тыква голосемянная" "/productsImages/product_341/images/pumpkin.jpg"
342 "Кабачки жареные (заготовка)" "/productsImages/product_342/images/zucchini.jpg"
343 "Баклажаны синие длинные" "/productsImages/product_343/images/eggplants.jpg"
344 "Морковь молодая мытая" "/productsImages/product_344/images/carrots.jpg"
345 "Салат айсберг хрустящий" "/productsImages/product_345/images/lettuce.jpg"
346 "Салат айсберг хрустящий" "/productsImages/product_346/images/lettuce.jpg"
347 "Брокколи зеленая" "/productsImages/product_347/images/cabbage.jpg"
348 "Лук репчатый золотистый" "/productsImages/product_348/images/onions.jpg"
349 "Шпинат витаминный" "/productsImages/product_349/images/lettuce.jpg"
350 "Перец болгарский красный" "/productsImages/product_350/images/peppers.jpg"
351 "Помидоры черри сладкие" "/productsImages/product_351/images/tomatoes.jpg"
352 "Кабачки нежные цукини" "/productsImages/product_352/images/zucchini.jpg"
353 "Редька дайкон сладкая" "/productsImages/product_353/images/radish.jpg"
354 "Капуста пекинская" "/productsImages/product_354/images/cabbage.jpg"
355 "Помидоры черри сладкие" "/productsImages/product_355/images/tomatoes.jpg"
356 "Чеснок свежий урожай" "/productsImages/product_356/images/garlic.jpg"
357 "Огурцы хрустящие с грядки" "/productsImages/product_357/images/cucumbers.jpg"
358 "Спаржа зеленая" "/productsImages/product_358/images/greens.jpg"
359 "Редька дайкон сладкая" "/productsImages/product_359/images/radish.jpg"
360 "Чеснок свежий урожай" "/productsImages/product_360/images/garlic.jpg"
361 "Лук-порей" "/productsImages/product_361/images/onions.jpg"
362 "Салат латук" "/productsImages/product_362/images/lettuce.jpg"
363 "Лук репчатый золотистый" "/productsImages/product_363/images/onions.jpg"
364 "Баклажаны синие длинные" "/productsImages/product_364/images/eggplants.jpg"
365 "Морковь молодая мытая" "/productsImages/product_365/images/carrots.jpg"
366 "Капуста пекинская" "/productsImages/product_366/images/cabbage.jpg"
367 "Розмарин душистый" "/productsImages/product_367/images/herbs.jpg"
368 "Капуста белокочанная свежая" "/productsImages/product_368/images/cabbage.jpg"
369 "Капуста белокочанная свежая" "/productsImages/product_369/images/cabbage.jpg"
370 "Микрозелень гороха" "/productsImages/product_370/images/greens.jpg"
371 "Тыква голосемянная" "/productsImages/product_371/images/pumpkin.jpg"
372 "Брокколи зеленая" "/productsImages/product_372/images/cabbage.jpg"
373 "Баклажаны синие длинные" "/productsImages/product_373/images/eggplants.jpg"
374 "Редис белый" "/productsImages/product_374/images/radish.jpg"
375 "Свекла столовая в пучке" "/productsImages/product_375/images/beetroot.jpg"
376 "Лук репчатый золотистый" "/productsImages/product_376/images/onions.jpg"
377 "Кабачки нежные цукини" "/productsImages/product_377/images/zucchini.jpg"
378 "Рукола пряная" "/productsImages/product_378/images/lettuce.jpg"
379 "Перец рамиро сладкий" "/productsImages/product_379/images/peppers.jpg"
380 "Розмарин душистый" "/productsImages/product_380/images/herbs.jpg"
381 "Розмарин душистый" "/productsImages/product_381/images/herbs.jpg"
382 "Лук-порей" "/productsImages/product_382/images/onions.jpg"
383 "Рукола пряная" "/productsImages/product_383/images/lettuce.jpg"
384 "Мята перечная" "/productsImages/product_384/images/herbs.jpg"
385 "Патиссоны мини" "/productsImages/product_385/images/zucchini.jpg"
386 "Чеснок свежий урожай" "/productsImages/product_386/images/garlic.jpg"
387 "Салат айсберг хрустящий" "/productsImages/product_387/images/lettuce.jpg"
388 "Капуста белокочанная свежая" "/productsImages/product_388/images/cabbage.jpg"
389 "Кинза свежая" "/productsImages/product_389/images/herbs.jpg"
390 "Свекла бордовая" "/productsImages/product_390/images/beetroot.jpg"
391 "Капуста пекинская" "/productsImages/product_391/images/cabbage.jpg"
392 "Лук репчатый золотистый" "/productsImages/product_392/images/onions.jpg"
393 "Редька дайкон сладкая" "/productsImages/product_393/images/radish.jpg"
394 "Перец рамиро сладкий" "/productsImages/product_394/images/peppers.jpg"
395 "Кабачки жареные (заготовка)" "/productsImages/product_395/images/zucchini.jpg"
396 "Перец рамиро сладкий" "/productsImages/product_396/images/peppers.jpg"
397 "Картофель молодой фермерский" "/productsImages/product_397/images/potatoes.jpg"
398 "Зелень петрушка+укроп" "/productsImages/product_398/images/herbs.jpg"
399 "Помидоры розовые бычье сердце" "/productsImages/product_399/images/tomatoes.jpg"
400 "Цветная капуста оранжевая" "/productsImages/product_400/images/cabbage.jpg"
401 "Салат латук" "/productsImages/product_401/images/lettuce.jpg"
402 "Брокколи зеленая" "/productsImages/product_402/images/cabbage.jpg"
403 "Брокколи зеленая" "/productsImages/product_403/images/cabbage.jpg"
404 "Микрозелень гороха" "/productsImages/product_404/images/greens.jpg"
405 "Сельдерей черешковый" "/productsImages/product_405/images/greens.jpg"
406 "Капуста пекинская" "/productsImages/product_406/images/cabbage.jpg"
407 "Перец рамиро сладкий" "/productsImages/product_407/images/peppers.jpg"
408 "Лук-порей" "/productsImages/product_408/images/onions.jpg"
409 "Помидоры черри сладкие" "/productsImages/product_409/images/tomatoes.jpg"
410 "Базилик фиолетовый" "/productsImages/product_410/images/herbs.jpg"
411 "Микрозелень гороха" "/productsImages/product_411/images/greens.jpg"
412 "Капуста пекинская" "/productsImages/product_412/images/cabbage.jpg"
413 "Картофель молодой фермерский" "/productsImages/product_413/images/potatoes.jpg"
414 "Салат айсберг хрустящий" "/productsImages/product_414/images/lettuce.jpg"
415 "Шпинат витаминный" "/productsImages/product_415/images/lettuce.jpg"
416 "Рукола пряная" "/productsImages/product_416/images/lettuce.jpg"
417 "Кабачки нежные цукини" "/productsImages/product_417/images/zucchini.jpg"
418 "Укроп душистый пучок" "/productsImages/product_418/images/herbs.jpg"
419 "Перец рамиро сладкий" "/productsImages/product_419/images/peppers.jpg"
420 "Сельдерей черешковый" "/productsImages/product_420/images/greens.jpg"
421 "Перец болгарский красный" "/productsImages/product_421/images/peppers.jpg"
422 "Помидоры розовые бычье сердце" "/productsImages/product_422/images/tomatoes.jpg"
423 "Помидоры розовые бычье сердце" "/productsImages/product_423/images/tomatoes.jpg"
424 "Тыква мускатная сладкая" "/productsImages/product_424/images/pumpkin.jpg"
425 "Укроп душистый пучок" "/productsImages/product_425/images/herbs.jpg"
426 "Лук-порей" "/productsImages/product_426/images/onions.jpg"
427 "Помидоры розовые бычье сердце" "/productsImages/product_427/images/tomatoes.jpg"
428 "Картофель красный мытый" "/productsImages/product_428/images/potatoes.jpg"
429 "Лук репчатый золотистый" "/productsImages/product_429/images/onions.jpg"
430 "Морковь каротель" "/productsImages/product_430/images/carrots.jpg"
431 "Перец рамиро сладкий" "/productsImages/product_431/images/peppers.jpg"
432 "Редька дайкон сладкая" "/productsImages/product_432/images/radish.jpg"
433 "Спаржа зеленая" "/productsImages/product_433/images/greens.jpg"
434 "Микрозелень гороха" "/productsImages/product_434/images/greens.jpg"
435 "Кабачок сквош" "/productsImages/product_435/images/zucchini.jpg"
436 "Перец халапеньо" "/productsImages/product_436/images/peppers.jpg"
437 "Редька дайкон сладкая" "/productsImages/product_437/images/radish.jpg"
438 "Лук репчатый золотистый" "/productsImages/product_438/images/onions.jpg"
439 "Свекла бордовая" "/productsImages/product_439/images/beetroot.jpg"
440 "Кинза свежая" "/productsImages/product_440/images/herbs.jpg"
441 "Капуста белокочанная свежая" "/productsImages/product_441/images/cabbage.jpg"
442 "Картофель по-деревенски" "/productsImages/product_442/images/potatoes.jpg"
443 "Рукола пряная" "/productsImages/product_443/images/lettuce.jpg"
444 "Рукола пряная" "/productsImages/product_444/images/lettuce.jpg"
445 "Чеснок свежий урожай" "/productsImages/product_445/images/garlic.jpg"
446 "Тыква мускатная сладкая" "/productsImages/product_446/images/pumpkin.jpg"
447 "Салат латук" "/productsImages/product_447/images/lettuce.jpg"
448 "Брокколи зеленая" "/productsImages/product_448/images/cabbage.jpg"
449 "Петрушка листовая нежная" "/productsImages/product_449/images/herbs.jpg"
450 "Петрушка листовая нежная" "/productsImages/product_450/images/herbs.jpg"
451 "Топинамбур полезный" "/productsImages/product_451/images/topinambur.jpg"
452 "Картофель красный мытый" "/productsImages/product_452/images/potatoes.jpg"
453 "Редис белый" "/productsImages/product_453/images/radish.jpg"
454 "Базилик фиолетовый" "/productsImages/product_454/images/herbs.jpg"
455 "Зелень петрушка+укроп" "/productsImages/product_455/images/herbs.jpg"
456 "Розмарин душистый" "/productsImages/product_456/images/herbs.jpg"
457 "Помидоры розовые бычье сердце" "/productsImages/product_457/images/tomatoes.jpg"
458 "Кабачки нежные цукини" "/productsImages/product_458/images/zucchini.jpg"
459 "Свекла бордовая" "/productsImages/product_459/images/beetroot.jpg"
460 "Тыква голосемянная" "/productsImages/product_460/images/pumpkin.jpg"
461 "Кинза свежая" "/productsImages/product_461/images/herbs.jpg"
462 "Перец халапеньо" "/productsImages/product_462/images/peppers.jpg"
463 "Розмарин душистый" "/productsImages/product_463/images/herbs.jpg"
464 "Морковь молодая мытая" "/productsImages/product_464/images/carrots.jpg"
465 "Тыква мускатная сладкая" "/productsImages/product_465/images/pumpkin.jpg"
466 "Баклажаны синие длинные" "/productsImages/product_466/images/eggplants.jpg"
467 "Салат айсберг хрустящий" "/productsImages/product_467/images/lettuce.jpg"
468 "Патиссоны мини" "/productsImages/product_468/images/zucchini.jpg"
469
470 "Чеснок свежий урожай" "/productsImages/product_470/images/garlic.jpg"
471 "Огурцы пупырчатые" "/productsImages/product_471/images/cucumbers.jpg"
472 "Кабачок сквош" "/productsImages/product_472/images/zucchini.jpg"
473 "Спаржа зеленая" "/productsImages/product_473/images/greens.jpg"
474 "Кабачки нежные цукини" "/productsImages/product_474/images/zucchini.jpg"
475 "Кабачки жареные (заготовка)" "/productsImages/product_475/images/zucchini.jpg"
476 "Свекла столовая в пучке" "/productsImages/product_476/images/beetroot.jpg"
477 "Топинамбур полезный" "/productsImages/product_477/images/topinambur.jpg"
478 "Лук-порей" "/productsImages/product_478/images/onions.jpg"
479 "Капуста белокочанная свежая" "/productsImages/product_479/images/cabbage.jpg"
480 "Лук-порей" "/productsImages/product_480/images/onions.jpg"
481 "Чеснок свежий урожай" "/productsImages/product_481/images/garlic.jpg"
482 "Помидоры розовые бычье сердце" "/productsImages/product_482/images/tomatoes.jpg"
483 "Лук репчатый золотистый" "/productsImages/product_483/images/onions.jpg"
484 "Топинамбур полезный" "/productsImages/product_484/images/topinambur.jpg"
485 "Огурцы хрустящие с грядки" "/productsImages/product_485/images/cucumbers.jpg"
486 "Кольраби нежная" "/productsImages/product_486/images/cabbage.jpg"
487 "Перец болгарский красный" "/productsImages/product_487/images/peppers.jpg"
488 "Лук репчатый золотистый" "/productsImages/product_488/images/onions.jpg"
489 "Топинамбур полезный" "/productsImages/product_489/images/topinambur.jpg"
490 "Кабачки жареные (заготовка)" "/productsImages/product_490/images/zucchini.jpg"
491 "Свекла бордовая" "/productsImages/product_491/images/beetroot.jpg"
492 "Редис сочный пучковый" "/productsImages/product_492/images/radish.jpg"
493 "Микрозелень гороха" "/productsImages/product_493/images/greens.jpg"
494 "Редис белый" "/productsImages/product_494/images/radish.jpg"
495 "Тыква голосемянная" "/productsImages/product_495/images/pumpkin.jpg"
496 "Розмарин душистый" "/productsImages/product_496/images/herbs.jpg"
497 "Свекла столовая в пучке" "/productsImages/product_497/images/beetroot.jpg"
498 "Салат айсберг хрустящий" "/productsImages/product_498/images/lettuce.jpg"
499 "Базилик фиолетовый" "/productsImages/product_499/images/herbs.jpg"
500 "Патиссоны мини" "/productsImages/product_500/images/zucchini.jpg"
501 "Лук репчатый золотистый" "/productsImages/product_501/images/onions.jpg"
502 "Брокколи зеленая" "/productsImages/product_502/images/cabbage.jpg"
503 "Лук репчатый золотистый" "/productsImages/product_503/images/onions.jpg"
504 "Салат айсберг хрустящий" "/productsImages/product_504/images/lettuce.jpg"
505 "Маринованные огурцы" "/productsImages/product_505/images/cucumbers.jpg"
506 "Кинза свежая" "/productsImages/product_506/images/herbs.jpg"
507 "Помидоры розовые бычье сердце" "/productsImages/product_507/images/tomatoes.jpg"
508 "Кабачки жареные (заготовка)" "/productsImages/product_508/images/zucchini.jpg"
509 "Базилик фиолетовый" "/productsImages/product_509/images/herbs.jpg"
510 "Картофель молодой фермерский" "/productsImages/product_510/images/potatoes.jpg"
511 "Розмарин душистый" "/productsImages/product_511/images/herbs.jpg"
512 "Лук-порей" "/productsImages/product_512/images/onions.jpg"
513 "Перец халапеньо" "/productsImages/product_513/images/peppers.jpg"
514 "Розмарин душистый" "/productsImages/product_514/images/herbs.jpg"
515 "Цветная капуста оранжевая" "/productsImages/product_515/images/cabbage.jpg"
516 "Салат айсберг хрустящий" "/productsImages/product_516/images/lettuce.jpg"
517 "Сельдерей черешковый" "/productsImages/product_517/images/greens.jpg"
518 "Редис белый" "/productsImages/product_518/images/radish.jpg"
519 "Чеснок свежий урожай" "/productsImages/product_519/images/garlic.jpg"
520 "Брокколи зеленая" "/productsImages/product_520/images/cabbage.jpg"
521 "Чеснок дикий" "/productsImages/product_521/images/garlic.jpg"
522 "Микрозелень гороха" "/productsImages/product_522/images/greens.jpg"
523 "Кабачок сквош" "/productsImages/product_523/images/zucchini.jpg"
524 "Чеснок свежий урожай" "/productsImages/product_524/images/garlic.jpg"
525 "Редис белый" "/productsImages/product_525/images/radish.jpg"
526 "Свекла бордовая" "/productsImages/product_526/images/beetroot.jpg"
527 "Лук репчатый золотистый" "/productsImages/product_527/images/onions.jpg"
528 "Картофель молодой фермерский" "/productsImages/product_528/images/potatoes.jpg"
529 "Морковь каротель" "/productsImages/product_529/images/carrots.jpg"
530 "Перец болгарский красный" "/productsImages/product_530/images/peppers.jpg"
531 "Брокколи зеленая" "/productsImages/product_531/images/cabbage.jpg"
532 "Редька дайкон сладкая" "/productsImages/product_532/images/radish.jpg"
533 "Помидоры черри сладкие" "/productsImages/product_533/images/tomatoes.jpg"
534 "Тыква мускатная сладкая" "/productsImages/product_534/images/pumpkin.jpg"
535 "Редька дайкон сладкая" "/productsImages/product_535/images/radish.jpg"
536 "Лук репчатый золотистый" "/productsImages/product_536/images/onions.jpg"
537 "Мята перечная" "/productsImages/product_537/images/herbs.jpg"
538 "Петрушка листовая нежная" "/productsImages/product_538/images/herbs.jpg"
539 "Базилик фиолетовый" "/productsImages/product_539/images/herbs.jpg"
540 "Морковь каротель" "/productsImages/product_540/images/carrots.jpg"
541 "Помидоры розовые бычье сердце" "/productsImages/product_541/images/tomatoes.jpg"
542 "Кабачки нежные цукини" "/productsImages/product_542/images/zucchini.jpg"
543 "Капуста белокочанная свежая" "/productsImages/product_543/images/cabbage.jpg"
544 "Помидоры розовые бычье сердце" "/productsImages/product_544/images/tomatoes.jpg"
545 "Мята перечная" "/productsImages/product_545/images/herbs.jpg"
546 "Цветная капуста оранжевая" "/productsImages/product_546/images/cabbage.jpg"
547 "Капуста белокочанная свежая" "/productsImages/product_547/images/cabbage.jpg"
548 "Огурцы пупырчатые" "/productsImages/product_548/images/cucumbers.jpg"
549 "Помидоры розовые бычье сердце" "/productsImages/product_549/images/tomatoes.jpg"
550 "Баклажаны синие длинные" "/productsImages/product_550/images/eggplants.jpg"
551 "Чеснок свежий урожай" "/productsImages/product_551/images/garlic.jpg"
552 "Чеснок дикий" "/productsImages/product_552/images/garlic.jpg"
553 "Кабачки жареные (заготовка)" "/productsImages/product_553/images/zucchini.jpg"
554 "Рукола пряная" "/productsImages/product_554/images/lettuce.jpg"
555 "Тыква голосемянная" "/productsImages/product_555/images/pumpkin.jpg"
556 "Огурцы пупырчатые" "/productsImages/product_556/images/cucumbers.jpg"
557 "Кинза свежая" "/productsImages/product_557/images/herbs.jpg"
558 "Брокколи зеленая" "/productsImages/product_558/images/cabbage.jpg"
559 "Микрозелень гороха" "/productsImages/product_559/images/greens.jpg"
560 "Капуста пекинская" "/productsImages/product_560/images/cabbage.jpg"
561 "Тыква голосемянная" "/productsImages/product_561/images/pumpkin.jpg"
562 "Брокколи зеленая" "/productsImages/product_562/images/cabbage.jpg"
563 "Брокколи зеленая" "/productsImages/product_563/images/cabbage.jpg"
564 "Помидоры розовые бычье сердце" "/productsImages/product_564/images/tomatoes.jpg"
565 "Морковь молодая мытая" "/productsImages/product_565/images/carrots.jpg"
566 "Цветная капуста оранжевая" "/productsImages/product_566/images/cabbage.jpg"
567 "Кольраби нежная" "/productsImages/product_567/images/cabbage.jpg"
568 "Соленые огурцы" "/productsImages/product_568/images/cucumbers.jpg"
569 "Шпинат витаминный" "/productsImages/product_569/images/lettuce.jpg"
570 "Картофель красный мытый" "/productsImages/product_570/images/potatoes.jpg"
571 "Огурцы маринованные по-домашнему" "/productsImages/product_571/images/cucumbers.jpg"
572 "Огурцы хрустящие с грядки" "/productsImages/product_572/images/cucumbers.jpg"
573 "Кольраби нежная" "/productsImages/product_573/images/cabbage.jpg"
574 "Базилик фиолетовый" "/productsImages/product_574/images/herbs.jpg"
575 "Капуста белокочанная свежая" "/productsImages/product_575/images/cabbage.jpg"
576 "Помидоры розовые бычье сердце" "/productsImages/product_576/images/tomatoes.jpg"
577 "Помидоры розовые бычье сердце" "/productsImages/product_577/images/tomatoes.jpg"
578 "Картофель красный мытый" "/productsImages/product_578/images/potatoes.jpg"
579 "Редис сочный пучковый" "/productsImages/product_579/images/radish.jpg"
580 "Тыква мускатная сладкая" "/productsImages/product_580/images/pumpkin.jpg"
581 "Салат латук" "/productsImages/product_581/images/lettuce.jpg"
582 "Брокколи зеленая" "/productsImages/product_582/images/cabbage.jpg"
583 "Свекла бордовая" "/productsImages/product_583/images/beetroot.jpg"
584 "Сельдерей черешковый" "/productsImages/product_584/images/greens.jpg"
585 "Морковь каротель" "/productsImages/product_585/images/carrots.jpg"
586 "Редис сочный пучковый" "/productsImages/product_586/images/radish.jpg"
587 "Редька дайкон сладкая" "/productsImages/product_587/images/radish.jpg"
588 "Кабачки жареные (заготовка)" "/productsImages/product_588/images/zucchini.jpg"
589 "Чеснок свежий урожай" "/productsImages/product_589/images/garlic.jpg"
590 "Морковь молодая мытая" "/productsImages/product_590/images/carrots.jpg"
591 "Цветная капуста оранжевая" "/productsImages/product_591/images/cabbage.jpg"
592 "Микрозелень гороха" "/productsImages/product_592/images/greens.jpg"
593 "Микрозелень гороха" "/productsImages/product_593/images/greens.jpg"
594 "Морковь мытая" "/productsImages/product_594/images/carrots.jpg"
595 "Патиссоны мини" "/productsImages/product_595/images/zucchini.jpg"
596 "Салат айсберг хрустящий" "/productsImages/product_596/images/lettuce.jpg"
597 "Картофель красный мытый" "/productsImages/product_597/images/potatoes.jpg"
598 "Зелень петрушка+укроп" "/productsImages/product_598/images/herbs.jpg"
599 "Брокколи зеленая" "/productsImages/product_599/images/cabbage.jpg"
600 "Кабачки нежные цукини" "/productsImages/product_600/images/zucchini.jpg"
601 "Огурцы хрустящие с грядки" "/productsImages/product_601/images/cucumbers.jpg"
602 "Огурцы пупырчатые" "/productsImages/product_602/images/cucumbers.jpg"
603 "Морковь молодая мытая" "/productsImages/product_603/images/carrots.jpg"
604 "Цветная капуста оранжевая" "/productsImages/product_604/images/cabbage.jpg"
605 "Розмарин душистый" "/productsImages/product_605/images/herbs.jpg"
606 "Огурцы пупырчатые" "/productsImages/product_606/images/cucumbers.jpg"
607 "Кинза свежая" "/productsImages/product_607/images/herbs.jpg"
608 "Укроп душистый пучок" "/productsImages/product_608/images/herbs.jpg"
609 "Микрозелень гороха" "/productsImages/product_609/images/greens.jpg"
610 "Салат айсберг хрустящий" "/productsImages/product_610/images/lettuce.jpg"
611 "Морковь спелая" "/productsImages/product_611/images/carrots.jpg"
612 "Петрушка листовая нежная" "/productsImages/product_612/images/herbs.jpg"
613 "Зелень петрушка+укроп" "/productsImages/product_613/images/herbs.jpg"
614 "Петрушка листовая нежная" "/productsImages/product_614/images/herbs.jpg"
615 "Картофель красный мытый" "/productsImages/product_615/images/potatoes.jpg"
616 "Помидоры черри сладкие" "/productsImages/product_616/images/tomatoes.jpg"
617 "Перец рамиро сладкий" "/productsImages/product_617/images/peppers.jpg"
618 "Свекла бордовая" "/productsImages/product_618/images/beetroot.jpg"
619 "Капуста белокочанная свежая" "/productsImages/product_619/images/cabbage.jpg"
620 "Перец болгарский красный" "/productsImages/product_620/images/peppers.jpg"
621 "Микрозелень гороха" "/productsImages/product_621/images/greens.jpg"
622 "Капуста белокочанная свежая" "/productsImages/product_622/images/cabbage.jpg"
623 "Свекла бордовая" "/productsImages/product_623/images/beetroot.jpg"
624 "Микрозелень гороха" "/productsImages/product_624/images/greens.jpg"
625 "Петрушка листовая нежная" "/productsImages/product_625/images/herbs.jpg"
626 "Лук репчатый золотистый" "/productsImages/product_626/images/onions.jpg"
627 "Розмарин душистый" "/productsImages/product_627/images/herbs.jpg"
628 "Цветная капуста оранжевая" "/productsImages/product_628/images/cabbage.jpg"
629 "Свекла бордовая" "/productsImages/product_629/images/beetroot.jpg"
630 "Огурцы хрустящие с грядки" "/productsImages/product_630/images/cucumbers.jpg"
631 "Помидоры розовые бычье сердце" "/productsImages/product_631/images/tomatoes.jpg"
632 "Кинза свежая" "/productsImages/product_632/images/herbs.jpg"
633 "Чеснок свежий урожай" "/productsImages/product_633/images/garlic.jpg"
634 "Кабачки жареные (заготовка)" "/productsImages/product_634/images/zucchini.jpg"
635 "Помидоры черри сладкие" "/productsImages/product_635/images/tomatoes.jpg"
'@

$created = 0
$copied = 0
$missing = 0
$skipped = 0

$lines = $Data -split "`r?`n"

foreach ($line in $lines) {
  if ([string]::IsNullOrWhiteSpace($line)) {
    continue
  }

  # Extract: ID and final imagePath
  if ($line -notmatch '^\s*(\d+)\s+".*?"\s+"([^"]+)"') {
    Write-Host "SKIP bad line: $line" -ForegroundColor DarkYellow
    $skipped++
    continue
  }

  $productId = $matches[1]
  $dbImagePath = $matches[2]

  $fileName = Split-Path $dbImagePath -Leaf

  # Source old shared file:
  # uploads/productsImages/onions.jpg
  $sourceFile = Join-Path $ProductsImagesDir $fileName

  # Destination new file:
  # uploads/productsImages/product_26/images/onions.jpg
  $relativeWithoutPrefix = $dbImagePath -replace '^/productsImages/', ''
  $destFile = Join-Path $ProductsImagesDir $relativeWithoutPrefix
  $destDir = Split-Path $destFile -Parent

  if (!(Test-Path $destDir)) {
    New-Item -ItemType Directory -Path $destDir -Force | Out-Null
    $created++
  }

  if (Test-Path $sourceFile) {
    Copy-Item -Path $sourceFile -Destination $destFile -Force
    Write-Host "OK product_${productId} -> $fileName" -ForegroundColor Green
    $copied++
  } else {
    Write-Host "MISSING source for product_${productId}: $sourceFile" -ForegroundColor Yellow
    $missing++
  }
}

Write-Host ""
Write-Host "Done."
Write-Host "Folders created: $created"
Write-Host "Images copied: $copied"
Write-Host "Missing source images: $missing"
Write-Host "Skipped lines: $skipped"